### ISSUE TITLE
libudev error

### ISSUE THREAD

**Issue by nuac87** [v1993/evdevhook2#25] opened 2024-09-15 03:00 UTC
Found CMake: /usr/bin/cmake (3.28.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libudev found: NO (tried pkgconfig and cmake)

src/meson.build:16:2: ERROR: Dependency "libudev" not found, tried pkgconfig and cmake

Fedora KDE 40

**Comment by v1993** [comment] 2024-09-15 11:48
You need to install development files for libudev, which README correctly lists as a dependency. Slightly confusingly, on fedora it's in package `systemd-devel`.

Closing as it's not a bug in the program; please use github discussions rather than issues if you need help in the future.

**Closed as not planned by v1993** 2024-09-15 11:48 UTC

**Comment by nuac87** [comment] 2024-09-15 20:57
Thank you I didn't realize that I had the wrong version of systemd-devel its fixed now, that is what I get for not sleeping lol
